In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
def get_spam_number(x):
    if x == 'spam':
        return 1
    return 0

In [5]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [6]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
x_train.shape

(4457,)

In [9]:
x_test.shape

(1115,)

In [10]:
type(x_train)

pandas.core.series.Series

In [13]:
x_train[:4]

1399     No did you check? I got his detailed message now
3586    Heart is empty without love.. Mind is empty wi...
668                 This pay is  &lt;DECIMAL&gt;  lakhs:)
2373    Watching tv lor... Y she so funny we bluff her...
Name: Message, dtype: object

In [14]:
type(y_train)

pandas.core.series.Series

In [17]:
y_train[:5]

1399    0
3586    0
668     0
2373    0
2100    1
Name: spam, dtype: int64

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59352 stored elements and shape (4457, 7721)>

In [19]:
type(x_train.values)

numpy.ndarray

In [21]:
x_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7721))

In [22]:
x_train_cv.shape

(4457, 7721)

In [25]:
v.get_feature_names_out()[1000:1050]

array(['anyone', 'anyones', 'anyplaces', 'anythiing', 'anythin',
       'anything', 'anythingtomorrow', 'anytime', 'anyway', 'anyways',
       'anywhere', 'aom', 'apart', 'apartment', 'apes', 'apo',
       'apologetic', 'apologise', 'apologize', 'apology', 'app',
       'apparently', 'appeal', 'appear', 'appendix', 'applebees',
       'apples', 'application', 'apply', 'applying', 'appointment',
       'appointments', 'appreciate', 'appreciated', 'approaches',
       'approaching', 'appropriate', 'approve', 'approx', 'apps', 'appt',
       'appy', 'april', 'aproach', 'apt', 'aptitude', 'ar', 'arab',
       'arabian', 'arcade'], dtype=object)

In [27]:
v.get_feature_names_out().shape

(7721,)

In [28]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_class_level_metadata_request_values',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',
 'ngram_range',
 'preprocessor',
 'set_params',
 'stop_words',
 'strip_accents',
 'token_pattern',
 'tokenizer',
 'transform',
 'vocabulary',
 'vocabulary_']

In [29]:
v.vocabulary_

{'no': 4783,
 'did': 2302,
 'you': 7684,
 'check': 1751,
 'got': 3205,
 'his': 3443,
 'detailed': 2276,
 'message': 4443,
 'now': 4833,
 'heart': 3387,
 'is': 3746,
 'empty': 2581,
 'without': 7528,
 'love': 4222,
 'mind': 4473,
 'wisdom': 7514,
 'eyes': 2741,
 'dreams': 2440,
 'amp': 952,
 'life': 4096,
 'frnds': 3020,
 'so': 6255,
 'alwys': 935,
 'be': 1276,
 'in': 3644,
 'touch': 6971,
 'good': 3189,
 'night': 4765,
 'sweet': 6631,
 'this': 6826,
 'pay': 5106,
 'lt': 4244,
 'decimal': 2204,
 'gt': 3265,
 'lakhs': 3991,
 'watching': 7378,
 'tv': 7057,
 'lor': 4202,
 'she': 6053,
 'funny': 3054,
 'we': 7391,
 'bluff': 1415,
 'her': 3415,
 'wat': 7375,
 'izzit': 3770,
 'because': 1286,
 'thk': 6827,
 'it': 3756,
 'impossible': 3636,
 'between': 1338,
 'us': 7184,
 'sms': 6235,
 'services': 6010,
 'for': 2945,
 'your': 7688,
 'inclusive': 3653,
 'text': 6761,
 'credits': 2065,
 'pls': 5238,
 'goto': 3210,
 'www': 7619,
 'comuk': 1939,
 'net': 4731,
 'login': 4175,
 'unsubscribe': 7151,
 'with': 7524,
 'stop': 6467,
 'extra': 2736,
 'charge': 1731,
 'help': 3406,
 '08700469649': 73,
 'po': 5247,
 'box420': 1472,
 'ip4': 3730,
 '5we': 561,
 'then': 6800,
 'better': 1336,
 'go': 3165,
 'sleep': 6192,
 'dun': 2482,
 'disturb': 2361,
 'liao': 4087,
 'wake': 7335,
 'up': 7156,
 'msg': 4608,
 'me': 4391,
 'mm': 4520,
 'umma': 7101,
 'ask': 1100,
 'vava': 7230,
 'also': 927,
 'to': 6911,
 'come': 1904,
 'tell': 6726,
 'him': 3438,
 'can': 1628,
 'play': 5221,
 'later': 4021,
 'together': 6921,
 'hello': 3403,
 'boytoy': 1482,
 'geeee': 3103,
 'missing': 4502,
 'today': 6917,
 'like': 4107,
 'send': 5987,
 'tm': 6902,
 'and': 964,
 'remind': 5670,
 'thinking': 6821,
 'of': 4883,
 'are': 1052,
 'loved': 4223,
 'loving': 4232,
 'kiss': 3940,
 'sorry': 6303,
 'll': 4155,
 'call': 1604,
 'lousy': 4219,
 'run': 5834,
 'already': 924,
 'back': 1199,
 'half': 3308,
 'dead': 2186,
 'hee': 3394,
 'afternoon': 854,
 'sexy': 6025,
 'buns': 1560,
 'how': 3523,
 'goes': 3171,
 'the': 6788,
 'job': 3825,
 'search': 5946,
 'my': 4653,
 'first': 2881,
 'thought': 6838,
 'as': 1090,
 'always': 934,
 'wish': 7516,
 'fine': 2864,
 'happy': 3339,
 'know': 3953,
 'adore': 823,
 'still': 6454,
 'working': 7572,
 'oh': 4901,
 'grand': 3226,
 'having': 3366,
 'bit': 1373,
 'party': 5085,
 'but': 1574,
 'doesn': 2387,
 'mention': 4432,
 'any': 996,
 'cover': 2038,
 'probably': 5410,
 'served': 6007,
 'two': 7065,
 'teams': 6712,
 'waiting': 7334,
 'some': 6267,
 'players': 5224,
 'don': 2405,
 'plan': 5212,
 'on': 4924,
 'staying': 6433,
 'prolly': 5429,
 'won': 7552,
 'til': 6875,
 'late': 4018,
 'sindu': 6152,
 'birla': 1367,
 'soft': 6259,
 'why': 7481,
 'cant': 1640,
 'here': 3416,
 'urgent': 7176,
 'have': 3361,
 'week': 7413,
 'free': 2992,
 'membership': 4425,
 'our': 4994,
 '100': 254,
 '000': 1,
 'prize': 5404,
 'jackpot': 3774,
 'txt': 7066,
 'word': 7566,
 'claim': 1819,
 '81010': 649,
 'dbuk': 2184,
 'lccltd': 4038,
 'pobox': 5249,
 '4403ldnw1a7rw18': 490,
 'do': 2377,
 'god': 3169,
 'created': 2060,
 'gap': 3078,
 'fingers': 2866,
 'that': 6784,
 'one': 4928,
 'who': 7473,
 'made': 4294,
 'comes': 1906,
 'fills': 2852,
 'those': 6834,
 'gaps': 3079,
 'by': 1590,
 'holding': 3469,
 'hand': 3317,
 'when': 7457,
 'guys': 3287,
 'leaving': 4055,
 'purity': 5480,
 'friendship': 3014,
 'not': 4820,
 'about': 757,
 'smiling': 6227,
 'after': 852,
 'reading': 5576,
 'forwarded': 2969,
 'its': 3763,
 'just': 3866,
 'seeing': 5965,
 'name': 4671,
 'gud': 3270,
 'evng': 2686,
 'wait': 7331,
 'till': 6876,
 'bus': 1567,
 'pick': 5183,
 'camera': 1624,
 'awarded': 1177,
 'sipix': 6160,
 'digital': 2319,
 '09061221066': 192,
 'fromm': 3027,
 'landline': 3998,
 'delivery': 2236,
 'within': 7527,
 '28': 375,
 'days': 2181,
 'av': 1158,
 'new': 4744,
 'number': 4847,
 'wil': 7493,
 'only': 4934,
 'use': 7188,
 'ta': 6655,
 'gr8': 3217,
 'poly': 5272,
 'tones': 6939,
 'all': 913,
 'mobs': 4540,
 'direct': 2334,
 '2u': 415,
 'rply': 5813,
 'title': 6893,
 '8007': 637,
 'eg': 2540,
 'breathe1': 1505,
 'titles': 6894,
 'crazyin': 2058,
 'sleepingwith': 6195,
 'finest': 2865,
 'ymca': 7678,
 'getzed': 3130,
 'co': 1867,
 'uk': 7095,
 'pobox365o4w45wq': 5255,
 '300p': 429,
 'thats': 6787,
 'going': 3176,
 'ruin': 5827,
 'thesis': 6809,
 'winner': 7507,
 'been': 1296,
 'specially': 6337,
 'selected': 5975,
 'receive': 5600,
 '1000': 255,
 'cash': 1675,
 'or': 4963,
 '2000': 345,
 'award': 1176,
 'speak': 6331,
 'live': 4147,
 'operator': 4950,
 '087147123779am': 119,
 '7pm': 630,
 'cost': 2016,
 '10p': 264,
 '449050000301': 495,
 'price': 5386,
 '09050000301': 162,
 'awake': 1175,
 'there': 6805,
 'snow': 6250,
 'wiskey': 7522,
 'brandy': 1490,
 'rum': 5831,
 'gin': 3142,
 'beer': 1298,
 'vodka': 7292,
 'scotch': 5928,
 'shampain': 6040,
 'wine': 7504,
 'kudi': 3968,
 'yarasu': 7652,
 'dhina': 2289,
 'vaazhthukkal': 7209,
 'wana': 7352,
 'see': 5964,
 'urself': 7183,
 'registered': 5644,
 'sinco': 6151,
 'payee': 5110,
 'log': 4172,
 'at': 1123,
 'icicibank': 3588,
 'com': 1898,
 'enter': 2608,
 'urn': 7182,
 'confirm': 1953,
 'beware': 1340,
 'frauds': 2986,
 'share': 6046,
 'disclose': 2348,
 'anyone': 1000,
 'win': 7498,
 'newest': 4746,
 'harry': 3349,
 'potter': 5315,
 'order': 4970,
 'phoenix': 5170,
 'book': 1432,
 'reply': 5696,
 'answer': 987,
 'questions': 5508,
 'chance': 1721,
 'among': 949,
 'readers': 5575,
 've': 7233,
 'down': 2425,
 'tea': 6706,
 'sure': 6602,
 'which': 7467,
 'flavour': 2900,
 'mobile': 4534,
 'was': 7368,
 'bonus': 1429,
 'caller': 1611,
 '02': 7,
 '09': 161,
 '03': 12,
 '2nd': 404,
 'attempt': 1133,
 'contact': 1975,
 '0871': 97,
 '872': 692,
 '9755': 728,
 'box95qu': 1475,
 'lesson': 4078,
 'will': 7496,
 'work': 7568,
 'sth': 6450,
 'get': 3121,
 'specs': 6340,
 'px3748': 5494,
 '1st': 333,
 'no1': 4784,
 'nokia': 4792,
 'tone': 6938,
 'ur': 7172,
 'mob': 4532,
 'every': 2670,
 'txting': 7072,
 'mates': 4366,
 '36504': 450,
 'w4': 7316,
 '5wq': 563,
 'norm': 4810,
 '150p': 303,
 '16': 314,
 'shant': 6044,
 'anymore': 999,
 'jia': 3819,
 'bec': 1284,
 'temple': 6736,
 'na': 4663,
 'gotta': 3211,
 'home': 3475,
 'cos': 2014,
 'out': 4996,
 'shopping': 6090,
 'frens': 3004,
 'present': 5369,
 'enough': 2606,
 'bud': 1548,
 'last': 4015,
 'most': 4582,
 'least': 4052,
 'paper': 5060,
 'morn': 4577,
 'aft': 851,
 'tmr': 6905,
 'hmmm': 3456,
 'dont': 2409,
 'opener': 4946,
 'yoyyooo': 7698,
 'change': 1723,
 'permissions': 5144,
 'drive': 2449,
 'mac': 4283,
 'usb': 7186,
 'flash': 2897,
 'honeybee': 3481,
 'said': 5858,
 'sweetest': 6632,
 'world': 7575,
 'laughed': 4026,
 'havnt': 3368,
 'met': 4450,
 'person': 5146,
 'moral': 4574,
 'even': 2663,
 'crack': 2047,
 'jokes': 3836,
 'gm': 3160,
 'gn': 3161,
 'ge': 3101,
 'where': 7461,
 '2morro': 399,
 'term': 6744,
 'over': 5013,
 '2nite': 406,
 'passion': 5091,
 'b4': 1187,
 'chat': 1742,
 '09099726481': 248,
 'luv': 4259,
 'dena': 2242,
 'calls': 1618,
 'minmobsmorelkpobox177hp51fl': 4481,
 'starshine': 6417,
 'does': 2386,
 'he': 3371,
 'crave': 2054,
 'yet': 7671,
 'ache': 789,
 'fuck': 3034,
 'sips': 6161,
 'cappuccino': 1645,
 'miss': 4498,
 'babe': 1192,
 'teasing': 6716,
 'playin': 5225,
 'space': 6321,
 'poker': 5267,
 'havent': 3364,
 'planning': 5217,
 'buy': 1578,
 'lido': 4093,
 '530': 549,
 'show': 6108,
 'finish': 2867,
 'tomarrow': 6932,
 'want': 7355,
 'court': 2035,
 'stand': 6408,
 'ok': 4906,
 'great': 3240,
 'thanx': 6782,
 'lot': 4209,
 'per': 5131,
 'request': 5703,
 'maangalyam': 4281,
 'alaipayuthe': 896,
 'has': 3350,
 'set': 6012,
 'callertune': 1613,
 'callers': 1612,
 'press': 5374,
 'copy': 2004,
 'friends': 3012,
 'stopped': 6473,
 'ice': 3586,
 'cream': 2059,
 'yar': 7651,
 'wan': 7350,
 'horse': 3504,
 'racing': 5521,
 'mah': 4304,
 'eat': 2513,
 'earlier': 2500,
 'ate': 1124,
 'chicken': 1774,
 'rice': 5760,
 'fran': 2981,
 'decided': 2202,
 'way': 7388,
 'im': 3621,
 'completely': 1929,
 'broke': 1525,
 'an': 960,
 'knackered': 3946,
 'bout': 1459,
 '2mrw': 403,
 'janx': 3788,
 'dads': 2147,
 'fone': 2934,
 'credit': 2063,
 'wow': 7593,
 'healthy': 3381,
 'old': 4917,
 'airport': 885,
 'rd': 5565,
 'anything': 1005,
 'else': 2566,
 'bathing': 1252,
 'dog': 2389,
 'yeah': 7658,
 'imma': 3627,
 'cause': 1689,
 'jay': 3794,
 'wants': 7359,
 'drugs': 2461,
 'meeting': 4410,
 'darren': 2167,
 'what': 7451,
 'time': 6877,
 'should': 6101,
 'friend': 3011,
 'around': 1076,
 'secret': 5954,
 'admirer': 820,
 'looking': 4194,
 'make': 4315,
 'find': 2862,
 'they': 6811,
 'reveal': 5747,
 'thinks': 6822,
 'special': 6333,
 '09058094565': 178,
 'finally': 2859,
 'lunch': 4255,
 'believe': 1314,
 'told': 6926,
 'oops': 4944,
 'let': 4080,
 'roommate': 5798,
 'done': 2407,
 'checkmate': 1755,
 'chess': 1767,
 'from': 3026,
 'persian': 5145,
 'phrase': 5180,
 'shah': 6033,
 'maat': 4282,
 'means': 4397,
 'king': 3936,
 'goodmorning': 3194,
 'day': 2180,
 'problem': 5411,
 'doing': 2396,
 'haf': 3299,
 'eaten': 2514,
 'yun': 7704,
 'ah': 872,
 'ubi': 7087,
 'say': 5906,
 'if': 3604,
 'tomorrow': 6936,
 '67441233': 584,
 'look': 4190,
 'irene': 3738,
 'ere': 2626,
 'bus8': 1568,
 '22': 358,
 '65': 579,
 '61': 570,
 '66': 581,
 '382': 454,
 'cres': 2068,
 'tech': 6717,
 'park': 5075,
 '6ph': 603,
 '5wkg': 562,
 'èn': 7719,
 'die': 2307,
 'accidentally': 778,
 'deleted': 2230,
 'suppose': 6598,
 'put': 5488,
 'sim': 6145,
 'archive': 1050,
 'haiz': 3307,
 'sad': 5851,
 'am': 936,
 'getting': 3129,
 'threats': 6843,
 'sales': 5864,
 'executive': 2706,
 'shifad': 6064,
 'raised': 5533,
 'complaint': 1925,
 'against': 859,
 'official': 4893,
 'meet': 4408,
 'combine': 1903,
 'parts': 5084,
 'da': 2141,
 'rest': 5729,
 'project': 5427,
 'notice': 4826,
 'shit': 6076,
 'mirror': 4492,
 'youre': 7689,
 'turning': 7054,
 'into': 3714,
 'right': 5765,
 'freak': 2987,
 'barely': 1229,
 'room': 5797,
 'too': 6950,
 'many': 4338,
 'fucking': 3037,
 'shoes': 6085,
 'man': 4324,
 'entry': 2616,
 'textpod': 6771,
 '40gb': 479,
 'ipod': 3735,
 '250': 368,
 'wk': 7533,
 'vpod': 7305,
 '81303': 651,
 'ts': 7034,
 'cs': 2087,
 'custcare': 2122,
 '08712405020': 112,
 'wahala': 7325,
 'remember': 5665,
 'need': 4713,
 'carry': 1670,
 'disturbing': 2363,
 'both': 1452,
 'ready': 5577,
 'dear': 2191,
 'voucher': 7303,
 'holder': 3468,
 'class': 1827,
 'lounge': 4218,
 'passes': 5090,
 'using': 7195,
 'holiday': 3471,
 '08704439680': 87,
 'booking': 1435,
 'quote': 5517,
 'long': 4187,
 'since': 6150,
 'screamed': 5935,
 'princess': 5393,
 'thank': 6778,
 'much': 4625,
 'selflessness': 5979,
 'plenty': 5235,
 'double': 2419,
 'mins': 4485,
 'linerental': 4124,
 'latest': 4022,
 'orange': 4966,
 'bluetooth': 1413,
 'mobiles': 4535,
 'mobileupd8': 4538,
 'very': 7248,
 'offers': 4891,
 '08000839402': 50,
 'call2optout': 1606,
 'lf56': 4085,
 'tonight': 6945,
 'neshanth': 4730,
 'tel': 6722,
 'year': 7659,
 'supply': 6595,
 'cds': 1700,
 'store': 6477,
 'choice': 1799,
 'worth': 7584,
 '500': 533,
 'weekly': 7417,
 'draw': 2436,
 'music': 4642,
 '87066': 686,
 'ldew': 4040,
 'subs16': 6533,
 '1win150ppmx3': 338,
 'tessy': 6754,
 'favor': 2798,
 'convey': 1990,
 'birthday': 1371,
 'wishes': 7518,
 'nimya': 4773,
 'dnt': 2376,
 'forget': 2952,
 'shijas': 6065,
 'wanna': 7353,
 'gym': 3290,
 'harri': 3348,
 'exhausted': 2709,
 'train': 6985,
 'morning': 4578,
 'pie': 5191,
 'well': 7429,
 'small': 6214,
 'house': 3519,
 'pretty': 5380,
 'wif': 7487,
 'hair': 3304,
 'cutting': 2134,
 'quite': 5513,
 'short': 6093,
 'leh': 4065,
 'rather': 5554,
 'prominent': 5430,
 'bite': 1376,
 'mark': 4346,
 'cheek': 1756,
 'join': 3831,
 'think': 6818,
 'usual': 7198,
 'guy': 3286,
 'passed': 5089,
 'ahold': 878,
 'anybody': 997,
 'throw': 6849,
 'hotel': 3512,
 'dusk': 2489,
 'game': 3073,
 'solve': 6265,
 'puzzles': 5493,
 'area': 1053,
 'thing': 6816,
 'lol': 4181,
 'trying': 7033,
 'little': 4146,
 'more': 4575,
 'interesting': 3706,
 'other': 4989,
 'news': 4749,
 'hassling': 3353,
 'weed': 7412,
 'andres': 967,
 'money': 4560,
 'haughaighgtujhyguj': 3355,
 'pizza': 5207,
 'hey': 3426,
 'doc': 2379,
 'nice': 4757,
 'shirt': 6074,
 'hubby': 3541,
 'fiting': 2885,
 'ones': 4929,
 'budget': 1549,
 'load': 4161,
 'card': 1650,
 'abi': 751,
 'hw': 3572,
 'keep': 3899,
 'posted': 5309,
 'mj': 4515,
 'wnt': 7544,
 'tlk': 6900,
 'wid': 7485,
 'yes': 7668,
 'thanks': 6779,
 'road': 5779,
 'shoot': 6087,
 'docs': 2382,
 'outside': 5006,
 'office': 4892,
 'take': 6665,
 'cool': 1997,
 'inches': 3648,
 'hope': 3490,
 'them': 6796,
 'big': 1352,
 'cartoon': 1673,
 'listening': 4141,
 'eve': 2661,
 'had': 3297,
 'church': 1812,
 'final': 2857,
 '150': 301,
 'discount': 2350,
 'vouchers': 7304,
 '85023': 677,
 'savamob': 5900,
 'member': 4423,
 'pobox84': 5257,
 'm263uz': 4273,
 '00': 0,
 'subs': 6532,
 'egg': 2542,
 'please': 5230,
 'sathya': 5894,
 'dint': 2332,
 'single': 6156,
 'saw': 5905,
 'situation': 6172,
 'shop': 6088,
 'drop': 2455,
 'either': 2551,
 '10k': 263,
 '5k': 555,
 'travel': 6999,
 '09064011000': 206,
 'ntt': 4841,
 'box': 1462,
 'cr01327bt': 2044,
 'fixedline': 2890,
 '150ppm': 307,
 'vary': 7227,
 'hi': 3429,
 'dude': 2475,
 'realy': 5587,
 'mising': 4497,
 'would': 7589,
 'lovely': 4225,
 'wot': 7586,
 'drinkin': 2445,
 'dancin': 2155,
 'eatin': 2515,
 'cinema': 1814,
 'aight': 881,
 'sounds': 6313,
 'tall': 6679,
 'hurt': 3563,
 'wasn': 7370,
 'surprised': 6609,
 'went': 7435,
 'spent': 6351,
 'evening': 2664,
 'french': 3003,
 'town': 6977,
 'fooled': 2939,
 'didn': 2304,
 'ride': 5764,
 'bike': 1355,
 'coming': 1909,
 'dinner': 2330,
 '09095350301': 243,
 'girls': 3146,
 'erotic': 2631,
 'ecstacy': 2521,
 '60p': 569,
 'min': 4470,
 'texts': 6772,
 '08712460324': 114,
 'nat': 4684,
 'rate': 5552,
 'math': 4367,
 'dunno': 2484,
 'mayb': 4383,
 'came': 1623,
 'fix': 2887,
 'ceiling': 1701,
 'course': 2034,
 'maths': 4371,
 'chapter': 1728,
 'month': 4569,
 'jesus': 3814,
 'armand': 1070,
 'really': 5586,
 'everybody': 2672,
 'liked': 4108,
 'ho': 3460,
 'these': 6807,
 'type': 7079,
 'words': 7567,
 '4u': 527,
 'congratulations': 1961,
 'cd': 1698,
 'gift': 3135,
 '125': 282,
 'guaranteed': 3268,
 'freeentry': 2995,
 'wkly': 7537,
 'xt': 7631,
 'tncs': 6910,
 'com1win150ppmx3age16': 1899,
 'dating': 2176,
 'service': 6009,
 'cal': 1600,
 '09064012103': 207,
 'box334sk38ch': 1468,
 'howz': 3530,
 'pain': 5043,
 'ystrday': 7701,
 'medicine': 4405,
 'sent': 5997,
 'email': 2570,
 'address': 815,
 'incomm': 3654,
 're': 5567,
 'were': 7438,
 'mcr': 4390,
 'boy': 1477,
 'glad': 3153,
 'wasted': 7373,
 'applebees': 1025,
 'nothing': 4825,
 'spook': 6377,
 'halloween': 3313,
 'collection': 1891,
 'logo': 4176,
 'pic': 5182,
 'plus': 5242,
 'eerie': 2535,
 'zed': 7714,
 '08701417012150p': 78,
 'daddy': 2146,
 'scream': 5934,
 'pleasure': 5233,
 'slap': 6190,
 'ass': 1109,
 'dick': 2299,
 'sake': 5859,
 'tallahassee': 6680,
 'specific': 6338,
 'regards': 5642,
 'jaklin': 3779,
 'idk': 3601,
 'switch': 6640,
 'dammit': 2150,
 'yr': 7699,
 'customer': 2124,
 'representative': 5701,
 '08714712394': 121,
 '10am': 262,
 'baby': 1194,
 'talk': 6673,
 'called': 1610,
 'left': 4059,
 'electricity': 2561,
 'fml': 2923,
 'height': 3397,
 'recycling': 5621,
 'read': 5574,
 'twice': 7061,
 'people': 5129,
 'spend': 6349,
 'earning': 2503,
 'same': 5872,
 'spending': 6350,
 'sending': 5989,
 'greetings': 3247,
 'joy': 3848,
 'happiness': 3338,
 'anyway': 1008,
 'evenings': 2665,
 'connection': 1963,
 'bw': 1586,
 'mu': 4623,
 'swing': 6638,
 'somebody': 6269,
 'door': 2412,
 'facebook': 2747,
 'impressively': 3640,
 'sensible': 5995,
 'early': 2501,
 'feel': 2810,
 'boring': 1446,
 'yours': 7692,
 'costa': 2017,
 'del': 2226,
 'sol': 6263,
 '5000': 534,
 'await': 1173,
 '09050090044': 171,
 'toclaim': 6916,
 'sae': 5852,
 'tc': 6702,
 'pobox334': 5253,
 'stockport': 6459,
 'sk38xh': 6179,
 '50': 532,
 'pm': 5245,
 'max10mins': 4379,
 'maybe': 4384,
 'pressies': 5375,
 'bin': 1363,
 'instant': 3695,
 '08715203028': 124,
 '9th': 738,
 'player': 5223,
 'wins': 7509,
 'optout': 4962,
 '08718727870': 149,
 'skateboarding': 6180,
 ...}

In [31]:
x_train_np = x_train_cv.toarray()
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7721))

In [34]:
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7721,))

In [35]:
np.where(x_train_np[0]!=0)

(array([1751, 2276, 2302, 3205, 3443, 4443, 4783, 4833, 7684]),)

In [40]:
x_train[:4][1399]

'No did you check? I got his detailed message now'

In [41]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [42]:
x_test_cv = v.transform(x_test)

In [45]:
from sklearn.metrics import classification_report

y_pred  = model.predict(x_test_cv)
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.99      1.00      0.99       952\n           1       0.99      0.94      0.97       163\n\n    accuracy                           0.99      1115\n   macro avg       0.99      0.97      0.98      1115\nweighted avg       0.99      0.99      0.99      1115\n'

In [46]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [47]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [48]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [49]:
y_pred = clf.predict(x_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       952
           1       0.99      0.94      0.97       163

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115